// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuumedjxepgdboirxydb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1dW1lZGp4ZXBnZGJvaXJ4eWRiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTAyMDUsImV4cCI6MjA2NTY4NjIwNX0.EKT3P8wulaqPKOfNQpE2FkSeFhA0EKkWPkuqOV4Gs-M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);